CREATE TABLE TB_BLOG_MST
(
    SEQ_NO NUMBER NOT NULL,
    TITLE  VARCHAR2(500) NOT NULL,
    DDABONG NUMBER NOT NULL,
    ADD_DATE DATE NOT NULL    
);

CREATE SEQUENCE SEQ_BLOG_MST;

INSERT INTO TB_BLOG_MST (SEQ_NO,TITLE,DDABONG,ADD_DATE) VALUES (SEQ_BLOG_MST.NEXTVAL,'자취 요리',0,SYSDATE);
INSERT INTO TB_BLOG_MST (SEQ_NO,TITLE,DDABONG,ADD_DATE) VALUES (SEQ_BLOG_MST.NEXTVAL,'독서 추천',0,SYSDATE);
INSERT INTO TB_BLOG_MST (SEQ_NO,TITLE,DDABONG,ADD_DATE) VALUES (SEQ_BLOG_MST.NEXTVAL,'나의 해방일지',0,SYSDATE);

ALTER TABLE TB_BLOG_MST ADD EDIT_DATE DATE ;

SELECT *
FROM TB_BLOG_MST;

UPDATE TB_BLOG_MST SET EDIT_DATE = (SELECT ADD_DATE FROM TB_BLOG_MST WHERE SEQ_NO='1') WHERE SEQ_NO='1';
UPDATE TB_BLOG_MST SET EDIT_DATE = (SELECT ADD_DATE FROM TB_BLOG_MST WHERE SEQ_NO='2') WHERE SEQ_NO='2';
UPDATE TB_BLOG_MST SET EDIT_DATE = (SELECT ADD_DATE FROM TB_BLOG_MST WHERE SEQ_NO='3') WHERE SEQ_NO='3';
